/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "outline": "#85948c",
        "surface-container-lowest": "#0b0e11",
        "on-surface-variant": "#bacac1",
        "on-secondary-fixed": "#181c21",
        "surface-container-low": "#191c1f",
        "primary-fixed-dim": "#2fe0aa",
        "surface-container": "#1d2023",
        "on-surface": "#e1e2e7",
        "tertiary-container": "#b3b8c0",
        "surface-tint": "#2fe0aa",
        "on-tertiary-fixed-variant": "#42474e",
        "on-secondary-fixed-variant": "#43474d",
        "surface-container-high": "#272a2e",
        "on-primary": "#003828",
        "surface": "#111417",
        "secondary": "#c3c6cd",
        "primary": "#44edb7",
        "surface-bright": "#37393d",
        "error-container": "#93000a",
        "on-primary-fixed": "#002116",
        "error": "#ffb4ab",
        "primary-fixed": "#59fdc5",
        "secondary-container": "#43474d",
        "outline-variant": "#3c4a43",
        "on-primary-fixed-variant": "#00513b",
        "inverse-surface": "#e1e2e7",
        "on-tertiary": "#2c3137",
        "tertiary-fixed": "#dee3eb",
        "tertiary-fixed-dim": "#c2c7cf",
        "primary-container": "#00d09c",
        "on-secondary": "#2d3136",
        "on-tertiary-container": "#44494f",
        "on-error": "#690005",
        "background": "#111417",
        "on-primary-container": "#00533c",
        "inverse-on-surface": "#2e3134",
        "on-error-container": "#ffdad6",
        "on-secondary-container": "#b2b5bc",
        "surface-dim": "#111417",
        "surface-variant": "#323538",
        "secondary-fixed": "#e0e2ea",
        "inverse-primary": "#006c4f",
        "tertiary": "#cfd3dc",
        "secondary-fixed-dim": "#c3c6cd",
        "on-tertiary-fixed": "#171c22",
        "on-background": "#e1e2e7",
        "surface-container-highest": "#323538"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "xs": "4px",
        "gutter": "20px",
        "md": "16px",
        "unit": "4px",
        "xl": "40px",
        "margin-mobile": "16px",
        "sm": "8px",
        "lg": "24px",
        "margin-desktop": "32px"
      },
      fontFamily: {
        "headline-md": ["Inter", "sans-serif"],
        "display": ["Inter", "sans-serif"],
        "label-sm": ["JetBrains Mono", "monospace"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "label-md": ["JetBrains Mono", "monospace"]
      },
      fontSize: {
        "headline-md": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
        "display": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "label-sm": ["10px", { "lineHeight": "14px", "letterSpacing": "0.05em", "fontWeight": "500" }],
        "headline-lg-mobile": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "body-lg": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "label-md": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "500" }]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
  ],
}
